@startuml

title SCOperand update() 関数ロジック

(*)  --> " 小数点の重複要求チェック"
If 重複チェック結果 then
    --> [NO] "小数点予約フラグ値のチェック"
        if 小数点予約フラグ値 then
            --> [YES] 文字列に小数点を挟みつつマージする
            --> (*)
        else
             --> [NO] 現在の文字列に要求値をマージする
        Endif
        --> 引数が小数点かチェック
        if 引数チェック
            --> [YES] 小数点予約フラグをTrueにする
            小数点予約フラグをTrueにする --> (*)
        else
             --> (*)
        Endif
else
    --> [YES(小数点が重複している)]  (*)
Endif

@enduml