@startuml
state 小数点なし

  小数点なし -->ドット含み状態 : 追加 ['・']
  小数点なし -->小数点なし : 追加 ['・' 以外]

state ドット含み状態 #FFDDDD {
    [*] --> 小数点予約
   小数点予約 -->小数点予約 : 追加 ['・' ]
   小数点予約 -->小数あり : 追加 ['・' 以外]
   小数あり -->小数あり : 追加 [ '・' は無視 ]
}

@enduml